[FIX] Addons path sequence issue while installing with Enterprise Edition
[Fix] Addons loading sequence issue

Issue: Odoo config file is loading enterprise addons first, instead of the odoo base module

File "/opt/odoo/enterprise/addons/web/controllers/main.py", line 34, in <module>
    from odoo.addons.base.models.qweb import QWeb
ModuleNotFoundError: No module named 'odoo.addons.base.models.qweb'


Solution: Change the sequence of the addons folder. Load odoo base addons first then odoo enterprise addons